import {
  AppleIcon,
  BabyIcon,
  BanknoteIcon,
  BathIcon,
  BatteryIcon,
  BeefIcon,
  BeerIcon,
  CandyIcon,
  CarrotIcon,
  CoffeeIcon,
  CookieIcon,
  CreditCardIcon,
  CroissantIcon,
  CupSodaIcon,
  EggIcon,
  FishIcon,
  GiftIcon,
  HamburgerIcon,
  HomeIcon,
  IceCreamConeIcon,
  type LucideIcon,
  MilkIcon,
  PawPrintIcon,
  PencilRulerIcon,
  PillIcon,
  SandwichIcon,
  SmartphoneIcon,
  SparklesIcon,
  SprayCanIcon,
  TagIcon,
  WheatIcon,
  WineIcon,
} from "lucide-react";
import type { CategoryIcon } from "@/domain/entities/category";
import type { PaymentType } from "@/domain/entities/sale";

export const PAYMENT_TYPE_ICONS: Record<PaymentType, LucideIcon> = {
  cash: BanknoteIcon,
  yape_plin: SmartphoneIcon,
  card: CreditCardIcon,
};

export const CATEGORY_ICON_COMPONENTS: Record<CategoryIcon, LucideIcon> = {
  bebidas: CupSodaIcon,
  licores: WineIcon,
  cervezas: BeerIcon,
  cafe: CoffeeIcon,
  snacks: CookieIcon,
  dulces: CandyIcon,
  helados: IceCreamConeIcon,
  panaderia: CroissantIcon,
  abarrotes: WheatIcon,
  lacteos: MilkIcon,
  huevos: EggIcon,
  carnes: BeefIcon,
  pescados: FishIcon,
  frutas: AppleIcon,
  verduras: CarrotIcon,
  alimentos: HamburgerIcon,
  comidas: SandwichIcon,
  limpieza: SprayCanIcon,
  higiene: BathIcon,
  bebes: BabyIcon,
  farmacia: PillIcon,
  mascotas: PawPrintIcon,
  regalos: GiftIcon,
  adornos: SparklesIcon,
  utiles: PencilRulerIcon,
  pilas: BatteryIcon,
  hogar: HomeIcon,
  otros: TagIcon,
};
