-- Numeric primary keys (id_<entity>) without losing data.
--
-- Hand-written (drizzle-kit would drop and recreate the columns): every table
-- is transformed in place, and drizzle's migrator runs it in one transaction,
-- so any failed check below rolls the whole migration back.
--
-- Nothing is deleted:
--   * the old uuid PK column `id` is renamed to `uuid` (still unique): the
--     offline idempotency key on sales / workers / audit_events;
--   * every old uuid FK column is renamed to `legacy_<col>_uuid` (nullable,
--     no constraint) and dropped later by 0009, once nothing reads it.
-- Existing rows are numbered oldest first (created_at).
-- Rollback: drizzle/rollback/0008_down.sql.

-- Fail fast instead of queueing behind (or blocking) the app, and never hold
-- the locks if the client connection drops mid-migration.
SET LOCAL lock_timeout = '10s';--> statement-breakpoint
SET LOCAL idle_in_transaction_session_timeout = '15s';--> statement-breakpoint

-- 1. Drop the FKs that point at the uuid primary keys.
ALTER TABLE "accounts" DROP CONSTRAINT "accounts_user_id_users_id_fk";--> statement-breakpoint
ALTER TABLE "sessions" DROP CONSTRAINT "sessions_user_id_users_id_fk";--> statement-breakpoint
ALTER TABLE "products" DROP CONSTRAINT "products_category_id_categories_id_fk";--> statement-breakpoint
ALTER TABLE "workers" DROP CONSTRAINT "workers_registered_by_users_id_fk";--> statement-breakpoint
ALTER TABLE "workers" DROP CONSTRAINT "workers_approved_by_users_id_fk";--> statement-breakpoint
ALTER TABLE "discount_policies" DROP CONSTRAINT "discount_policies_created_by_users_id_fk";--> statement-breakpoint
ALTER TABLE "sales" DROP CONSTRAINT "sales_cashier_id_users_id_fk";--> statement-breakpoint
ALTER TABLE "sales" DROP CONSTRAINT "sales_courtesy_approved_by_users_id_fk";--> statement-breakpoint
ALTER TABLE "sales" DROP CONSTRAINT "sales_worker_id_workers_id_fk";--> statement-breakpoint
ALTER TABLE "sales" DROP CONSTRAINT "sales_policy_id_discount_policies_id_fk";--> statement-breakpoint
ALTER TABLE "sale_items" DROP CONSTRAINT "sale_items_sale_id_sales_id_fk";--> statement-breakpoint
ALTER TABLE "sale_items" DROP CONSTRAINT "sale_items_product_id_products_id_fk";--> statement-breakpoint
ALTER TABLE "stock_levels" DROP CONSTRAINT "stock_levels_product_id_products_id_fk";--> statement-breakpoint
ALTER TABLE "stock_levels" DROP CONSTRAINT "stock_levels_location_id_locations_id_fk";--> statement-breakpoint
ALTER TABLE "stock_movements" DROP CONSTRAINT "stock_movements_product_id_products_id_fk";--> statement-breakpoint
ALTER TABLE "stock_movements" DROP CONSTRAINT "stock_movements_location_id_locations_id_fk";--> statement-breakpoint
ALTER TABLE "stock_movements" DROP CONSTRAINT "stock_movements_actor_id_users_id_fk";--> statement-breakpoint
ALTER TABLE "loyalty_ledger" DROP CONSTRAINT "loyalty_ledger_worker_id_workers_id_fk";--> statement-breakpoint
ALTER TABLE "loyalty_ledger" DROP CONSTRAINT "loyalty_ledger_sale_id_sales_id_fk";--> statement-breakpoint
ALTER TABLE "loyalty_ledger" DROP CONSTRAINT "loyalty_ledger_sale_id_unique";--> statement-breakpoint
ALTER TABLE "audit_events" DROP CONSTRAINT "audit_events_actor_id_users_id_fk";--> statement-breakpoint
ALTER TABLE "audit_events" DROP CONSTRAINT "audit_events_worker_id_workers_id_fk";--> statement-breakpoint
ALTER TABLE "stock_levels" DROP CONSTRAINT "stock_levels_product_id_location_id_pk";--> statement-breakpoint
DROP INDEX "products_category_id_idx";--> statement-breakpoint
DROP INDEX "sales_worker_created_idx";--> statement-breakpoint
DROP INDEX "sales_cashier_created_idx";--> statement-breakpoint
DROP INDEX "stock_movements_ref_unique";--> statement-breakpoint
DROP INDEX "stock_movements_product_idx";--> statement-breakpoint
DROP INDEX "loyalty_ledger_worker_idx";--> statement-breakpoint
DROP INDEX "audit_events_worker_type_idx";--> statement-breakpoint

-- 2. Numeric primary keys: id -> uuid, new id_<entity> numbered oldest first.
ALTER TABLE "users" RENAME COLUMN "id" TO "uuid";--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "id_user" integer;--> statement-breakpoint
UPDATE "users" t SET "id_user" = r.n FROM (SELECT "uuid", row_number() OVER (ORDER BY "created_at", "uuid") AS n FROM "users") r WHERE t."uuid" = r."uuid";--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "id_user" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "id_user" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_user_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
SELECT setval('"users_id_user_seq"', (SELECT coalesce(max("id_user"), 0) + 1 FROM "users"), false);--> statement-breakpoint
ALTER TABLE "users" DROP CONSTRAINT "users_pkey";--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id_user");--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_uuid_unique" UNIQUE ("uuid");--> statement-breakpoint

ALTER TABLE "categories" RENAME COLUMN "id" TO "uuid";--> statement-breakpoint
ALTER TABLE "categories" ADD COLUMN "id_category" integer;--> statement-breakpoint
UPDATE "categories" t SET "id_category" = r.n FROM (SELECT "uuid", row_number() OVER (ORDER BY "created_at", "uuid") AS n FROM "categories") r WHERE t."uuid" = r."uuid";--> statement-breakpoint
ALTER TABLE "categories" ALTER COLUMN "id_category" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "categories" ALTER COLUMN "id_category" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "categories_id_category_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
SELECT setval('"categories_id_category_seq"', (SELECT coalesce(max("id_category"), 0) + 1 FROM "categories"), false);--> statement-breakpoint
ALTER TABLE "categories" DROP CONSTRAINT "categories_pkey";--> statement-breakpoint
ALTER TABLE "categories" ADD CONSTRAINT "categories_pkey" PRIMARY KEY ("id_category");--> statement-breakpoint
ALTER TABLE "categories" ADD CONSTRAINT "categories_uuid_unique" UNIQUE ("uuid");--> statement-breakpoint

ALTER TABLE "products" RENAME COLUMN "id" TO "uuid";--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "id_product" integer;--> statement-breakpoint
UPDATE "products" t SET "id_product" = r.n FROM (SELECT "uuid", row_number() OVER (ORDER BY "created_at", "uuid") AS n FROM "products") r WHERE t."uuid" = r."uuid";--> statement-breakpoint
ALTER TABLE "products" ALTER COLUMN "id_product" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "products" ALTER COLUMN "id_product" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "products_id_product_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
SELECT setval('"products_id_product_seq"', (SELECT coalesce(max("id_product"), 0) + 1 FROM "products"), false);--> statement-breakpoint
ALTER TABLE "products" DROP CONSTRAINT "products_pkey";--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_pkey" PRIMARY KEY ("id_product");--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_uuid_unique" UNIQUE ("uuid");--> statement-breakpoint

ALTER TABLE "workers" RENAME COLUMN "id" TO "uuid";--> statement-breakpoint
ALTER TABLE "workers" ADD COLUMN "id_worker" integer;--> statement-breakpoint
UPDATE "workers" t SET "id_worker" = r.n FROM (SELECT "uuid", row_number() OVER (ORDER BY "created_at", "uuid") AS n FROM "workers") r WHERE t."uuid" = r."uuid";--> statement-breakpoint
ALTER TABLE "workers" ALTER COLUMN "id_worker" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "workers" ALTER COLUMN "id_worker" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "workers_id_worker_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
SELECT setval('"workers_id_worker_seq"', (SELECT coalesce(max("id_worker"), 0) + 1 FROM "workers"), false);--> statement-breakpoint
ALTER TABLE "workers" DROP CONSTRAINT "workers_pkey";--> statement-breakpoint
ALTER TABLE "workers" ADD CONSTRAINT "workers_pkey" PRIMARY KEY ("id_worker");--> statement-breakpoint
ALTER TABLE "workers" ADD CONSTRAINT "workers_uuid_unique" UNIQUE ("uuid");--> statement-breakpoint

ALTER TABLE "discount_policies" RENAME COLUMN "id" TO "uuid";--> statement-breakpoint
ALTER TABLE "discount_policies" ADD COLUMN "id_policy" integer;--> statement-breakpoint
UPDATE "discount_policies" t SET "id_policy" = r.n FROM (SELECT "uuid", row_number() OVER (ORDER BY "created_at", "uuid") AS n FROM "discount_policies") r WHERE t."uuid" = r."uuid";--> statement-breakpoint
ALTER TABLE "discount_policies" ALTER COLUMN "id_policy" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "discount_policies" ALTER COLUMN "id_policy" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "discount_policies_id_policy_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
SELECT setval('"discount_policies_id_policy_seq"', (SELECT coalesce(max("id_policy"), 0) + 1 FROM "discount_policies"), false);--> statement-breakpoint
ALTER TABLE "discount_policies" DROP CONSTRAINT "discount_policies_pkey";--> statement-breakpoint
ALTER TABLE "discount_policies" ADD CONSTRAINT "discount_policies_pkey" PRIMARY KEY ("id_policy");--> statement-breakpoint
ALTER TABLE "discount_policies" ADD CONSTRAINT "discount_policies_uuid_unique" UNIQUE ("uuid");--> statement-breakpoint

ALTER TABLE "sales" RENAME COLUMN "id" TO "uuid";--> statement-breakpoint
ALTER TABLE "sales" ADD COLUMN "id_sale" integer;--> statement-breakpoint
UPDATE "sales" t SET "id_sale" = r.n FROM (SELECT "uuid", row_number() OVER (ORDER BY "client_created_at", "created_at", "uuid") AS n FROM "sales") r WHERE t."uuid" = r."uuid";--> statement-breakpoint
ALTER TABLE "sales" ALTER COLUMN "id_sale" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "sales" ALTER COLUMN "id_sale" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "sales_id_sale_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
SELECT setval('"sales_id_sale_seq"', (SELECT coalesce(max("id_sale"), 0) + 1 FROM "sales"), false);--> statement-breakpoint
ALTER TABLE "sales" DROP CONSTRAINT "sales_pkey";--> statement-breakpoint
ALTER TABLE "sales" ADD CONSTRAINT "sales_pkey" PRIMARY KEY ("id_sale");--> statement-breakpoint
ALTER TABLE "sales" ADD CONSTRAINT "sales_uuid_unique" UNIQUE ("uuid");--> statement-breakpoint

-- sale_items has no created_at: numbered in the order of their sale.
ALTER TABLE "sale_items" RENAME COLUMN "id" TO "uuid";--> statement-breakpoint
ALTER TABLE "sale_items" ADD COLUMN "id_sale_item" integer;--> statement-breakpoint
UPDATE "sale_items" t SET "id_sale_item" = r.n FROM (SELECT i."uuid", row_number() OVER (ORDER BY s."client_created_at", s."uuid", i."uuid") AS n FROM "sale_items" i JOIN "sales" s ON s."uuid" = i."sale_id") r WHERE t."uuid" = r."uuid";--> statement-breakpoint
ALTER TABLE "sale_items" ALTER COLUMN "id_sale_item" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "sale_items" ALTER COLUMN "id_sale_item" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "sale_items_id_sale_item_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
SELECT setval('"sale_items_id_sale_item_seq"', (SELECT coalesce(max("id_sale_item"), 0) + 1 FROM "sale_items"), false);--> statement-breakpoint
ALTER TABLE "sale_items" DROP CONSTRAINT "sale_items_pkey";--> statement-breakpoint
ALTER TABLE "sale_items" ADD CONSTRAINT "sale_items_pkey" PRIMARY KEY ("id_sale_item");--> statement-breakpoint
ALTER TABLE "sale_items" ADD CONSTRAINT "sale_items_uuid_unique" UNIQUE ("uuid");--> statement-breakpoint

ALTER TABLE "locations" RENAME COLUMN "id" TO "uuid";--> statement-breakpoint
ALTER TABLE "locations" ADD COLUMN "id_location" integer;--> statement-breakpoint
UPDATE "locations" t SET "id_location" = r.n FROM (SELECT "uuid", row_number() OVER (ORDER BY "created_at", "kind", "uuid") AS n FROM "locations") r WHERE t."uuid" = r."uuid";--> statement-breakpoint
ALTER TABLE "locations" ALTER COLUMN "id_location" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "locations" ALTER COLUMN "id_location" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "locations_id_location_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
SELECT setval('"locations_id_location_seq"', (SELECT coalesce(max("id_location"), 0) + 1 FROM "locations"), false);--> statement-breakpoint
ALTER TABLE "locations" DROP CONSTRAINT "locations_pkey";--> statement-breakpoint
ALTER TABLE "locations" ADD CONSTRAINT "locations_pkey" PRIMARY KEY ("id_location");--> statement-breakpoint
ALTER TABLE "locations" ADD CONSTRAINT "locations_uuid_unique" UNIQUE ("uuid");--> statement-breakpoint

ALTER TABLE "stock_movements" RENAME COLUMN "id" TO "uuid";--> statement-breakpoint
ALTER TABLE "stock_movements" ADD COLUMN "id_movement" integer;--> statement-breakpoint
UPDATE "stock_movements" t SET "id_movement" = r.n FROM (SELECT "uuid", row_number() OVER (ORDER BY "created_at", "uuid") AS n FROM "stock_movements") r WHERE t."uuid" = r."uuid";--> statement-breakpoint
ALTER TABLE "stock_movements" ALTER COLUMN "id_movement" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "stock_movements" ALTER COLUMN "id_movement" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_movements_id_movement_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
SELECT setval('"stock_movements_id_movement_seq"', (SELECT coalesce(max("id_movement"), 0) + 1 FROM "stock_movements"), false);--> statement-breakpoint
ALTER TABLE "stock_movements" DROP CONSTRAINT "stock_movements_pkey";--> statement-breakpoint
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_pkey" PRIMARY KEY ("id_movement");--> statement-breakpoint
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_uuid_unique" UNIQUE ("uuid");--> statement-breakpoint

ALTER TABLE "loyalty_ledger" RENAME COLUMN "id" TO "uuid";--> statement-breakpoint
ALTER TABLE "loyalty_ledger" ADD COLUMN "id_loyalty" integer;--> statement-breakpoint
UPDATE "loyalty_ledger" t SET "id_loyalty" = r.n FROM (SELECT "uuid", row_number() OVER (ORDER BY "created_at", "uuid") AS n FROM "loyalty_ledger") r WHERE t."uuid" = r."uuid";--> statement-breakpoint
ALTER TABLE "loyalty_ledger" ALTER COLUMN "id_loyalty" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "loyalty_ledger" ALTER COLUMN "id_loyalty" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "loyalty_ledger_id_loyalty_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
SELECT setval('"loyalty_ledger_id_loyalty_seq"', (SELECT coalesce(max("id_loyalty"), 0) + 1 FROM "loyalty_ledger"), false);--> statement-breakpoint
ALTER TABLE "loyalty_ledger" DROP CONSTRAINT "loyalty_ledger_pkey";--> statement-breakpoint
ALTER TABLE "loyalty_ledger" ADD CONSTRAINT "loyalty_ledger_pkey" PRIMARY KEY ("id_loyalty");--> statement-breakpoint
ALTER TABLE "loyalty_ledger" ADD CONSTRAINT "loyalty_ledger_uuid_unique" UNIQUE ("uuid");--> statement-breakpoint

ALTER TABLE "audit_events" RENAME COLUMN "id" TO "uuid";--> statement-breakpoint
ALTER TABLE "audit_events" ADD COLUMN "id_audit" integer;--> statement-breakpoint
UPDATE "audit_events" t SET "id_audit" = r.n FROM (SELECT "uuid", row_number() OVER (ORDER BY "created_at", "occurred_at", "uuid") AS n FROM "audit_events") r WHERE t."uuid" = r."uuid";--> statement-breakpoint
ALTER TABLE "audit_events" ALTER COLUMN "id_audit" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "audit_events" ALTER COLUMN "id_audit" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_events_id_audit_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
SELECT setval('"audit_events_id_audit_seq"', (SELECT coalesce(max("id_audit"), 0) + 1 FROM "audit_events"), false);--> statement-breakpoint
ALTER TABLE "audit_events" DROP CONSTRAINT "audit_events_pkey";--> statement-breakpoint
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_pkey" PRIMARY KEY ("id_audit");--> statement-breakpoint
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_uuid_unique" UNIQUE ("uuid");--> statement-breakpoint
-- A courtesy is approved before its sale exists: keeps pointing at sales.uuid.
ALTER TABLE "audit_events" RENAME COLUMN "sale_id" TO "sale_uuid";--> statement-breakpoint

-- 3. Foreign keys: old uuid column -> legacy_<col>_uuid, new integer column
--    resolved through the parent's uuid.
ALTER TABLE "accounts" RENAME COLUMN "user_id" TO "legacy_user_id_uuid";--> statement-breakpoint
ALTER TABLE "accounts" ALTER COLUMN "legacy_user_id_uuid" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "accounts" ADD COLUMN "id_user" integer;--> statement-breakpoint
UPDATE "accounts" c SET "id_user" = p."id_user" FROM "users" p WHERE p."uuid" = c."legacy_user_id_uuid";--> statement-breakpoint
ALTER TABLE "accounts" ALTER COLUMN "id_user" SET NOT NULL;--> statement-breakpoint

ALTER TABLE "sessions" RENAME COLUMN "user_id" TO "legacy_user_id_uuid";--> statement-breakpoint
ALTER TABLE "sessions" ALTER COLUMN "legacy_user_id_uuid" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "id_user" integer;--> statement-breakpoint
UPDATE "sessions" c SET "id_user" = p."id_user" FROM "users" p WHERE p."uuid" = c."legacy_user_id_uuid";--> statement-breakpoint
ALTER TABLE "sessions" ALTER COLUMN "id_user" SET NOT NULL;--> statement-breakpoint

ALTER TABLE "products" RENAME COLUMN "category_id" TO "legacy_category_id_uuid";--> statement-breakpoint
ALTER TABLE "products" ALTER COLUMN "legacy_category_id_uuid" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "id_category" integer;--> statement-breakpoint
UPDATE "products" c SET "id_category" = p."id_category" FROM "categories" p WHERE p."uuid" = c."legacy_category_id_uuid";--> statement-breakpoint
ALTER TABLE "products" ALTER COLUMN "id_category" SET NOT NULL;--> statement-breakpoint

ALTER TABLE "workers" RENAME COLUMN "registered_by" TO "legacy_registered_by_uuid";--> statement-breakpoint
ALTER TABLE "workers" ADD COLUMN "registered_by" integer;--> statement-breakpoint
UPDATE "workers" c SET "registered_by" = p."id_user" FROM "users" p WHERE p."uuid" = c."legacy_registered_by_uuid";--> statement-breakpoint
ALTER TABLE "workers" RENAME COLUMN "approved_by" TO "legacy_approved_by_uuid";--> statement-breakpoint
ALTER TABLE "workers" ADD COLUMN "approved_by" integer;--> statement-breakpoint
UPDATE "workers" c SET "approved_by" = p."id_user" FROM "users" p WHERE p."uuid" = c."legacy_approved_by_uuid";--> statement-breakpoint

ALTER TABLE "discount_policies" RENAME COLUMN "created_by" TO "legacy_created_by_uuid";--> statement-breakpoint
ALTER TABLE "discount_policies" ADD COLUMN "created_by" integer;--> statement-breakpoint
UPDATE "discount_policies" c SET "created_by" = p."id_user" FROM "users" p WHERE p."uuid" = c."legacy_created_by_uuid";--> statement-breakpoint

ALTER TABLE "sales" RENAME COLUMN "cashier_id" TO "legacy_cashier_id_uuid";--> statement-breakpoint
ALTER TABLE "sales" ALTER COLUMN "legacy_cashier_id_uuid" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "sales" ADD COLUMN "id_cashier" integer;--> statement-breakpoint
UPDATE "sales" c SET "id_cashier" = p."id_user" FROM "users" p WHERE p."uuid" = c."legacy_cashier_id_uuid";--> statement-breakpoint
ALTER TABLE "sales" ALTER COLUMN "id_cashier" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "sales" RENAME COLUMN "courtesy_approved_by" TO "legacy_courtesy_approved_by_uuid";--> statement-breakpoint
ALTER TABLE "sales" ADD COLUMN "courtesy_approved_by" integer;--> statement-breakpoint
UPDATE "sales" c SET "courtesy_approved_by" = p."id_user" FROM "users" p WHERE p."uuid" = c."legacy_courtesy_approved_by_uuid";--> statement-breakpoint
ALTER TABLE "sales" RENAME COLUMN "worker_id" TO "legacy_worker_id_uuid";--> statement-breakpoint
ALTER TABLE "sales" ADD COLUMN "id_worker" integer;--> statement-breakpoint
UPDATE "sales" c SET "id_worker" = p."id_worker" FROM "workers" p WHERE p."uuid" = c."legacy_worker_id_uuid";--> statement-breakpoint
ALTER TABLE "sales" RENAME COLUMN "policy_id" TO "legacy_policy_id_uuid";--> statement-breakpoint
ALTER TABLE "sales" ADD COLUMN "id_policy" integer;--> statement-breakpoint
UPDATE "sales" c SET "id_policy" = p."id_policy" FROM "discount_policies" p WHERE p."uuid" = c."legacy_policy_id_uuid";--> statement-breakpoint

ALTER TABLE "sale_items" RENAME COLUMN "sale_id" TO "legacy_sale_id_uuid";--> statement-breakpoint
ALTER TABLE "sale_items" ALTER COLUMN "legacy_sale_id_uuid" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "sale_items" ADD COLUMN "id_sale" integer;--> statement-breakpoint
UPDATE "sale_items" c SET "id_sale" = p."id_sale" FROM "sales" p WHERE p."uuid" = c."legacy_sale_id_uuid";--> statement-breakpoint
ALTER TABLE "sale_items" ALTER COLUMN "id_sale" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "sale_items" RENAME COLUMN "product_id" TO "legacy_product_id_uuid";--> statement-breakpoint
ALTER TABLE "sale_items" ALTER COLUMN "legacy_product_id_uuid" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "sale_items" ADD COLUMN "id_product" integer;--> statement-breakpoint
UPDATE "sale_items" c SET "id_product" = p."id_product" FROM "products" p WHERE p."uuid" = c."legacy_product_id_uuid";--> statement-breakpoint
ALTER TABLE "sale_items" ALTER COLUMN "id_product" SET NOT NULL;--> statement-breakpoint

ALTER TABLE "stock_levels" RENAME COLUMN "product_id" TO "legacy_product_id_uuid";--> statement-breakpoint
ALTER TABLE "stock_levels" ALTER COLUMN "legacy_product_id_uuid" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "stock_levels" ADD COLUMN "id_product" integer;--> statement-breakpoint
UPDATE "stock_levels" c SET "id_product" = p."id_product" FROM "products" p WHERE p."uuid" = c."legacy_product_id_uuid";--> statement-breakpoint
ALTER TABLE "stock_levels" ALTER COLUMN "id_product" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "stock_levels" RENAME COLUMN "location_id" TO "legacy_location_id_uuid";--> statement-breakpoint
ALTER TABLE "stock_levels" ALTER COLUMN "legacy_location_id_uuid" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "stock_levels" ADD COLUMN "id_location" integer;--> statement-breakpoint
UPDATE "stock_levels" c SET "id_location" = p."id_location" FROM "locations" p WHERE p."uuid" = c."legacy_location_id_uuid";--> statement-breakpoint
ALTER TABLE "stock_levels" ALTER COLUMN "id_location" SET NOT NULL;--> statement-breakpoint

ALTER TABLE "stock_movements" RENAME COLUMN "product_id" TO "legacy_product_id_uuid";--> statement-breakpoint
ALTER TABLE "stock_movements" ALTER COLUMN "legacy_product_id_uuid" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "stock_movements" ADD COLUMN "id_product" integer;--> statement-breakpoint
UPDATE "stock_movements" c SET "id_product" = p."id_product" FROM "products" p WHERE p."uuid" = c."legacy_product_id_uuid";--> statement-breakpoint
ALTER TABLE "stock_movements" ALTER COLUMN "id_product" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "stock_movements" RENAME COLUMN "location_id" TO "legacy_location_id_uuid";--> statement-breakpoint
ALTER TABLE "stock_movements" ALTER COLUMN "legacy_location_id_uuid" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "stock_movements" ADD COLUMN "id_location" integer;--> statement-breakpoint
UPDATE "stock_movements" c SET "id_location" = p."id_location" FROM "locations" p WHERE p."uuid" = c."legacy_location_id_uuid";--> statement-breakpoint
ALTER TABLE "stock_movements" ALTER COLUMN "id_location" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "stock_movements" RENAME COLUMN "actor_id" TO "legacy_actor_id_uuid";--> statement-breakpoint
ALTER TABLE "stock_movements" ADD COLUMN "id_actor" integer;--> statement-breakpoint
UPDATE "stock_movements" c SET "id_actor" = p."id_user" FROM "users" p WHERE p."uuid" = c."legacy_actor_id_uuid";--> statement-breakpoint

ALTER TABLE "loyalty_ledger" RENAME COLUMN "worker_id" TO "legacy_worker_id_uuid";--> statement-breakpoint
ALTER TABLE "loyalty_ledger" ALTER COLUMN "legacy_worker_id_uuid" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "loyalty_ledger" ADD COLUMN "id_worker" integer;--> statement-breakpoint
UPDATE "loyalty_ledger" c SET "id_worker" = p."id_worker" FROM "workers" p WHERE p."uuid" = c."legacy_worker_id_uuid";--> statement-breakpoint
ALTER TABLE "loyalty_ledger" ALTER COLUMN "id_worker" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "loyalty_ledger" RENAME COLUMN "sale_id" TO "legacy_sale_id_uuid";--> statement-breakpoint
ALTER TABLE "loyalty_ledger" ADD COLUMN "id_sale" integer;--> statement-breakpoint
UPDATE "loyalty_ledger" c SET "id_sale" = p."id_sale" FROM "sales" p WHERE p."uuid" = c."legacy_sale_id_uuid";--> statement-breakpoint

ALTER TABLE "audit_events" RENAME COLUMN "actor_id" TO "legacy_actor_id_uuid";--> statement-breakpoint
ALTER TABLE "audit_events" ADD COLUMN "id_actor" integer;--> statement-breakpoint
UPDATE "audit_events" c SET "id_actor" = p."id_user" FROM "users" p WHERE p."uuid" = c."legacy_actor_id_uuid";--> statement-breakpoint
ALTER TABLE "audit_events" RENAME COLUMN "worker_id" TO "legacy_worker_id_uuid";--> statement-breakpoint
ALTER TABLE "audit_events" ADD COLUMN "id_worker" integer;--> statement-breakpoint
UPDATE "audit_events" c SET "id_worker" = p."id_worker" FROM "workers" p WHERE p."uuid" = c."legacy_worker_id_uuid";--> statement-breakpoint

-- 4. Guard: a nullable FK that had a value must have resolved to one. (The
--    NOT NULL ones are already guarded by SET NOT NULL above.) Any miss
--    aborts the whole migration.
DO $$
DECLARE
  misses integer;
BEGIN
  SELECT
      (SELECT count(*) FROM "workers" WHERE "legacy_registered_by_uuid" IS NOT NULL AND "registered_by" IS NULL)
    + (SELECT count(*) FROM "workers" WHERE "legacy_approved_by_uuid" IS NOT NULL AND "approved_by" IS NULL)
    + (SELECT count(*) FROM "discount_policies" WHERE "legacy_created_by_uuid" IS NOT NULL AND "created_by" IS NULL)
    + (SELECT count(*) FROM "sales" WHERE "legacy_courtesy_approved_by_uuid" IS NOT NULL AND "courtesy_approved_by" IS NULL)
    + (SELECT count(*) FROM "sales" WHERE "legacy_worker_id_uuid" IS NOT NULL AND "id_worker" IS NULL)
    + (SELECT count(*) FROM "sales" WHERE "legacy_policy_id_uuid" IS NOT NULL AND "id_policy" IS NULL)
    + (SELECT count(*) FROM "stock_movements" WHERE "legacy_actor_id_uuid" IS NOT NULL AND "id_actor" IS NULL)
    + (SELECT count(*) FROM "loyalty_ledger" WHERE "legacy_sale_id_uuid" IS NOT NULL AND "id_sale" IS NULL)
    + (SELECT count(*) FROM "audit_events" WHERE "legacy_actor_id_uuid" IS NOT NULL AND "id_actor" IS NULL)
    + (SELECT count(*) FROM "audit_events" WHERE "legacy_worker_id_uuid" IS NOT NULL AND "id_worker" IS NULL)
  INTO misses;
  IF misses > 0 THEN
    RAISE EXCEPTION '0008_numeric_ids: % foreign key value(s) did not resolve', misses;
  END IF;
END $$;--> statement-breakpoint

-- 5. Constraints and indexes on the numeric columns.
ALTER TABLE "stock_levels" ADD CONSTRAINT "stock_levels_id_product_id_location_pk" PRIMARY KEY ("id_product", "id_location");--> statement-breakpoint
ALTER TABLE "loyalty_ledger" ADD CONSTRAINT "loyalty_ledger_id_sale_unique" UNIQUE ("id_sale");--> statement-breakpoint
ALTER TABLE "accounts" ADD CONSTRAINT "accounts_id_user_users_id_user_fk" FOREIGN KEY ("id_user") REFERENCES "public"."users"("id_user") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_id_actor_users_id_user_fk" FOREIGN KEY ("id_actor") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_id_worker_workers_id_worker_fk" FOREIGN KEY ("id_worker") REFERENCES "public"."workers"("id_worker") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discount_policies" ADD CONSTRAINT "discount_policies_created_by_users_id_user_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loyalty_ledger" ADD CONSTRAINT "loyalty_ledger_id_worker_workers_id_worker_fk" FOREIGN KEY ("id_worker") REFERENCES "public"."workers"("id_worker") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loyalty_ledger" ADD CONSTRAINT "loyalty_ledger_id_sale_sales_id_sale_fk" FOREIGN KEY ("id_sale") REFERENCES "public"."sales"("id_sale") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_id_category_categories_id_category_fk" FOREIGN KEY ("id_category") REFERENCES "public"."categories"("id_category") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sale_items" ADD CONSTRAINT "sale_items_id_sale_sales_id_sale_fk" FOREIGN KEY ("id_sale") REFERENCES "public"."sales"("id_sale") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sale_items" ADD CONSTRAINT "sale_items_id_product_products_id_product_fk" FOREIGN KEY ("id_product") REFERENCES "public"."products"("id_product") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales" ADD CONSTRAINT "sales_id_cashier_users_id_user_fk" FOREIGN KEY ("id_cashier") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales" ADD CONSTRAINT "sales_courtesy_approved_by_users_id_user_fk" FOREIGN KEY ("courtesy_approved_by") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales" ADD CONSTRAINT "sales_id_worker_workers_id_worker_fk" FOREIGN KEY ("id_worker") REFERENCES "public"."workers"("id_worker") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales" ADD CONSTRAINT "sales_id_policy_discount_policies_id_policy_fk" FOREIGN KEY ("id_policy") REFERENCES "public"."discount_policies"("id_policy") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_id_user_users_id_user_fk" FOREIGN KEY ("id_user") REFERENCES "public"."users"("id_user") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_levels" ADD CONSTRAINT "stock_levels_id_product_products_id_product_fk" FOREIGN KEY ("id_product") REFERENCES "public"."products"("id_product") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_levels" ADD CONSTRAINT "stock_levels_id_location_locations_id_location_fk" FOREIGN KEY ("id_location") REFERENCES "public"."locations"("id_location") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_id_product_products_id_product_fk" FOREIGN KEY ("id_product") REFERENCES "public"."products"("id_product") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_id_location_locations_id_location_fk" FOREIGN KEY ("id_location") REFERENCES "public"."locations"("id_location") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_id_actor_users_id_user_fk" FOREIGN KEY ("id_actor") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workers" ADD CONSTRAINT "workers_registered_by_users_id_user_fk" FOREIGN KEY ("registered_by") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workers" ADD CONSTRAINT "workers_approved_by_users_id_user_fk" FOREIGN KEY ("approved_by") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_events_worker_type_idx" ON "audit_events" USING btree ("id_worker","type","occurred_at");--> statement-breakpoint
CREATE INDEX "loyalty_ledger_worker_idx" ON "loyalty_ledger" USING btree ("id_worker");--> statement-breakpoint
CREATE INDEX "products_category_id_idx" ON "products" USING btree ("id_category");--> statement-breakpoint
CREATE INDEX "sales_worker_created_idx" ON "sales" USING btree ("id_worker","client_created_at");--> statement-breakpoint
CREATE INDEX "sales_cashier_created_idx" ON "sales" USING btree ("id_cashier","client_created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "stock_movements_ref_unique" ON "stock_movements" USING btree ("type","ref_id","id_product","id_location");--> statement-breakpoint
CREATE INDEX "stock_movements_product_idx" ON "stock_movements" USING btree ("id_product","created_at");
