CREATE TABLE "supplier_categories" (
	"id_supplier" integer NOT NULL,
	"id_category" integer NOT NULL,
	CONSTRAINT "supplier_categories_id_supplier_id_category_pk" PRIMARY KEY("id_supplier","id_category")
);
--> statement-breakpoint
CREATE TABLE "suppliers" (
	"id_supplier" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "suppliers_id_supplier_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ruc" text,
	"business_name" text NOT NULL,
	"trade_name" text,
	"contact_name" text,
	"phone" text,
	"email" text,
	"address" text,
	"notes" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "suppliers_ruc_unique" UNIQUE("ruc")
);
--> statement-breakpoint
ALTER TABLE "supplier_categories" ADD CONSTRAINT "supplier_categories_id_supplier_suppliers_id_supplier_fk" FOREIGN KEY ("id_supplier") REFERENCES "public"."suppliers"("id_supplier") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_categories" ADD CONSTRAINT "supplier_categories_id_category_categories_id_category_fk" FOREIGN KEY ("id_category") REFERENCES "public"."categories"("id_category") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "supplier_categories_category_idx" ON "supplier_categories" USING btree ("id_category");