CREATE TABLE "stock_lots" (
	"id_lot" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_lots_id_lot_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_product" integer NOT NULL,
	"id_location" integer NOT NULL,
	"expires_at" date NOT NULL,
	"quantity" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "categories" ADD COLUMN "tracks_expiry" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "categories" ADD COLUMN "expiry_warning_days" integer DEFAULT 30 NOT NULL;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "tracks_expiry" boolean;--> statement-breakpoint
ALTER TABLE "stock_lots" ADD CONSTRAINT "stock_lots_id_product_products_id_product_fk" FOREIGN KEY ("id_product") REFERENCES "public"."products"("id_product") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_lots" ADD CONSTRAINT "stock_lots_id_location_locations_id_location_fk" FOREIGN KEY ("id_location") REFERENCES "public"."locations"("id_location") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "stock_lots_product_location_expiry_unique" ON "stock_lots" USING btree ("id_product","id_location","expires_at");--> statement-breakpoint
CREATE INDEX "stock_lots_expires_idx" ON "stock_lots" USING btree ("expires_at");--> statement-breakpoint
-- Bebidas and Snacks control expiry (agreed with the owner); the rest stays off.
UPDATE "categories" SET "tracks_expiry" = true WHERE lower("name") IN ('bebidas', 'snacks');
