CREATE TABLE "product_presentations" (
	"id_presentation" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_presentations_id_presentation_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_product" integer NOT NULL,
	"name" text NOT NULL,
	"id_parent_presentation" integer,
	"qty_of_parent" integer NOT NULL,
	"units_total" integer NOT NULL,
	"barcode" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "product_presentations_barcode_unique" UNIQUE("barcode")
);
--> statement-breakpoint
ALTER TABLE "product_presentations" ADD CONSTRAINT "product_presentations_id_product_products_id_product_fk" FOREIGN KEY ("id_product") REFERENCES "public"."products"("id_product") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_presentations" ADD CONSTRAINT "product_presentations_parent_fk" FOREIGN KEY ("id_parent_presentation") REFERENCES "public"."product_presentations"("id_presentation") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "product_presentations_name_unique" ON "product_presentations" USING btree ("id_product",lower("name"));