CREATE TYPE "public"."receipt_doc_type" AS ENUM('factura', 'boleta', 'guia', 'ninguno');--> statement-breakpoint
CREATE TABLE "goods_receipt_items" (
	"id_receipt_item" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "goods_receipt_items_id_receipt_item_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_receipt" integer NOT NULL,
	"id_product" integer NOT NULL,
	"id_presentation" integer,
	"quantity" integer NOT NULL,
	"units" integer NOT NULL,
	"line_total" numeric(10, 2) NOT NULL,
	"unit_cost" numeric(12, 4) NOT NULL,
	"is_bonus" boolean DEFAULT false NOT NULL,
	"expires_at" date
);
--> statement-breakpoint
CREATE TABLE "goods_receipts" (
	"id_receipt" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "goods_receipts_id_receipt_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uuid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"id_supplier" integer,
	"id_location" integer NOT NULL,
	"doc_type" "receipt_doc_type" DEFAULT 'ninguno' NOT NULL,
	"doc_number" text,
	"total" numeric(10, 2) NOT NULL,
	"note" text,
	"id_created_by" integer,
	"received_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "goods_receipts_uuid_unique" UNIQUE("uuid")
);
--> statement-breakpoint
CREATE TABLE "stock_transfer_items" (
	"id_transfer_item" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_transfer_items_id_transfer_item_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_transfer" integer NOT NULL,
	"id_product" integer NOT NULL,
	"units" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stock_transfers" (
	"id_transfer" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_transfers_id_transfer_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uuid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"id_from_location" integer NOT NULL,
	"id_to_location" integer NOT NULL,
	"note" text,
	"id_created_by" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "stock_transfers_uuid_unique" UNIQUE("uuid")
);
--> statement-breakpoint
ALTER TABLE "products" ALTER COLUMN "price_cost" SET DATA TYPE numeric(12, 4);--> statement-breakpoint
ALTER TABLE "sale_items" ALTER COLUMN "unit_cost" SET DATA TYPE numeric(12, 4);--> statement-breakpoint
ALTER TABLE "stock_movements" ALTER COLUMN "unit_cost" SET DATA TYPE numeric(12, 4);--> statement-breakpoint
ALTER TABLE "goods_receipt_items" ADD CONSTRAINT "goods_receipt_items_id_receipt_goods_receipts_id_receipt_fk" FOREIGN KEY ("id_receipt") REFERENCES "public"."goods_receipts"("id_receipt") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goods_receipt_items" ADD CONSTRAINT "goods_receipt_items_id_product_products_id_product_fk" FOREIGN KEY ("id_product") REFERENCES "public"."products"("id_product") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goods_receipt_items" ADD CONSTRAINT "goods_receipt_items_presentation_fk" FOREIGN KEY ("id_presentation") REFERENCES "public"."product_presentations"("id_presentation") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goods_receipts" ADD CONSTRAINT "goods_receipts_id_supplier_suppliers_id_supplier_fk" FOREIGN KEY ("id_supplier") REFERENCES "public"."suppliers"("id_supplier") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goods_receipts" ADD CONSTRAINT "goods_receipts_id_location_locations_id_location_fk" FOREIGN KEY ("id_location") REFERENCES "public"."locations"("id_location") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goods_receipts" ADD CONSTRAINT "goods_receipts_id_created_by_users_id_user_fk" FOREIGN KEY ("id_created_by") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_transfer_items" ADD CONSTRAINT "stock_transfer_items_id_transfer_stock_transfers_id_transfer_fk" FOREIGN KEY ("id_transfer") REFERENCES "public"."stock_transfers"("id_transfer") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_transfer_items" ADD CONSTRAINT "stock_transfer_items_id_product_products_id_product_fk" FOREIGN KEY ("id_product") REFERENCES "public"."products"("id_product") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_transfers" ADD CONSTRAINT "stock_transfers_id_from_location_locations_id_location_fk" FOREIGN KEY ("id_from_location") REFERENCES "public"."locations"("id_location") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_transfers" ADD CONSTRAINT "stock_transfers_id_to_location_locations_id_location_fk" FOREIGN KEY ("id_to_location") REFERENCES "public"."locations"("id_location") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_transfers" ADD CONSTRAINT "stock_transfers_id_created_by_users_id_user_fk" FOREIGN KEY ("id_created_by") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "goods_receipt_items_receipt_idx" ON "goods_receipt_items" USING btree ("id_receipt");--> statement-breakpoint
CREATE UNIQUE INDEX "goods_receipts_document_unique" ON "goods_receipts" USING btree ("id_supplier","doc_type","doc_number") WHERE "goods_receipts"."doc_number" is not null;--> statement-breakpoint
CREATE INDEX "goods_receipts_received_idx" ON "goods_receipts" USING btree ("received_at");