CREATE TYPE "public"."purchase_order_status" AS ENUM('pending', 'partial', 'received', 'cancelled');--> statement-breakpoint
CREATE TABLE "purchase_order_items" (
	"id_order_item" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "purchase_order_items_id_order_item_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_order" integer NOT NULL,
	"id_product" integer NOT NULL,
	"id_presentation" integer,
	"quantity" integer NOT NULL,
	"units" integer NOT NULL,
	"estimated_total" numeric(10, 2)
);
--> statement-breakpoint
CREATE TABLE "purchase_orders" (
	"id_order" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "purchase_orders_id_order_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_supplier" integer NOT NULL,
	"status" "purchase_order_status" DEFAULT 'pending' NOT NULL,
	"expected_at" date,
	"estimated_total" numeric(10, 2),
	"note" text,
	"id_created_by" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "goods_receipts" ADD COLUMN "id_order" integer;--> statement-breakpoint
ALTER TABLE "purchase_order_items" ADD CONSTRAINT "purchase_order_items_id_order_purchase_orders_id_order_fk" FOREIGN KEY ("id_order") REFERENCES "public"."purchase_orders"("id_order") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_order_items" ADD CONSTRAINT "purchase_order_items_id_product_products_id_product_fk" FOREIGN KEY ("id_product") REFERENCES "public"."products"("id_product") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_order_items" ADD CONSTRAINT "purchase_order_items_presentation_fk" FOREIGN KEY ("id_presentation") REFERENCES "public"."product_presentations"("id_presentation") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_id_supplier_suppliers_id_supplier_fk" FOREIGN KEY ("id_supplier") REFERENCES "public"."suppliers"("id_supplier") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_id_created_by_users_id_user_fk" FOREIGN KEY ("id_created_by") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "purchase_order_items_order_idx" ON "purchase_order_items" USING btree ("id_order");--> statement-breakpoint
CREATE INDEX "purchase_orders_status_idx" ON "purchase_orders" USING btree ("status");--> statement-breakpoint
ALTER TABLE "goods_receipts" ADD CONSTRAINT "goods_receipts_id_order_purchase_orders_id_order_fk" FOREIGN KEY ("id_order") REFERENCES "public"."purchase_orders"("id_order") ON DELETE no action ON UPDATE no action;