CREATE TYPE "public"."discrepancy_status" AS ENUM('open', 'replenished', 'credited', 'written_off', 'kept', 'returned');--> statement-breakpoint
CREATE TABLE "receipt_discrepancies" (
	"id_discrepancy" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "receipt_discrepancies_id_discrepancy_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uuid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"id_receipt" integer NOT NULL,
	"id_receipt_item" integer NOT NULL,
	"id_product" integer NOT NULL,
	"units" integer NOT NULL,
	"amount" numeric(10, 2) NOT NULL,
	"status" "discrepancy_status" DEFAULT 'open' NOT NULL,
	"resolution_note" text,
	"id_resolved_by" integer,
	"resolved_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "receipt_discrepancies_uuid_unique" UNIQUE("uuid")
);
--> statement-breakpoint
ALTER TABLE "goods_receipt_items" ADD COLUMN "received_units" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "receipt_discrepancies" ADD CONSTRAINT "receipt_discrepancies_id_receipt_goods_receipts_id_receipt_fk" FOREIGN KEY ("id_receipt") REFERENCES "public"."goods_receipts"("id_receipt") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "receipt_discrepancies" ADD CONSTRAINT "receipt_discrepancies_id_product_products_id_product_fk" FOREIGN KEY ("id_product") REFERENCES "public"."products"("id_product") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "receipt_discrepancies" ADD CONSTRAINT "receipt_discrepancies_id_resolved_by_users_id_user_fk" FOREIGN KEY ("id_resolved_by") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "receipt_discrepancies" ADD CONSTRAINT "receipt_discrepancies_item_fk" FOREIGN KEY ("id_receipt_item") REFERENCES "public"."goods_receipt_items"("id_receipt_item") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "receipt_discrepancies_status_idx" ON "receipt_discrepancies" USING btree ("status");