CREATE TYPE "public"."count_item_status" AS ENUM('matched', 'pending', 'approved', 'rejected');--> statement-breakpoint
CREATE TABLE "stock_count_items" (
	"id_count_item" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_count_items_id_count_item_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_count" integer NOT NULL,
	"id_product" integer NOT NULL,
	"expected" integer NOT NULL,
	"counted" integer NOT NULL,
	"lots" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"status" "count_item_status" NOT NULL,
	"id_reviewed_by" integer,
	"reviewed_at" timestamp with time zone,
	"review_note" text
);
--> statement-breakpoint
CREATE TABLE "stock_counts" (
	"id_count" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_counts_id_count_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uuid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"id_location" integer NOT NULL,
	"id_counted_by" integer,
	"counted_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "stock_counts_uuid_unique" UNIQUE("uuid")
);
--> statement-breakpoint
ALTER TABLE "stock_count_items" ADD CONSTRAINT "stock_count_items_id_count_stock_counts_id_count_fk" FOREIGN KEY ("id_count") REFERENCES "public"."stock_counts"("id_count") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_count_items" ADD CONSTRAINT "stock_count_items_id_product_products_id_product_fk" FOREIGN KEY ("id_product") REFERENCES "public"."products"("id_product") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_count_items" ADD CONSTRAINT "stock_count_items_id_reviewed_by_users_id_user_fk" FOREIGN KEY ("id_reviewed_by") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_counts" ADD CONSTRAINT "stock_counts_id_location_locations_id_location_fk" FOREIGN KEY ("id_location") REFERENCES "public"."locations"("id_location") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_counts" ADD CONSTRAINT "stock_counts_id_counted_by_users_id_user_fk" FOREIGN KEY ("id_counted_by") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "stock_count_items_status_idx" ON "stock_count_items" USING btree ("status");--> statement-breakpoint
CREATE INDEX "stock_count_items_product_idx" ON "stock_count_items" USING btree ("id_product");