CREATE TYPE "public"."cash_movement_type" AS ENUM('in', 'out');--> statement-breakpoint
CREATE TYPE "public"."cash_shift_status" AS ENUM('open', 'closed', 'reviewed');--> statement-breakpoint
CREATE TABLE "cash_movements" (
	"id_cash_movement" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cash_movements_id_cash_movement_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uuid" uuid NOT NULL,
	"shift_uuid" uuid NOT NULL,
	"type" "cash_movement_type" NOT NULL,
	"amount" numeric(10, 2) NOT NULL,
	"reason" text NOT NULL,
	"occurred_at" timestamp with time zone NOT NULL,
	"id_created_by" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "cash_movements_uuid_unique" UNIQUE("uuid")
);
--> statement-breakpoint
CREATE TABLE "cash_shifts" (
	"id_shift" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cash_shifts_id_shift_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uuid" uuid NOT NULL,
	"id_cashier" integer NOT NULL,
	"status" "cash_shift_status" DEFAULT 'open' NOT NULL,
	"opened_at" timestamp with time zone NOT NULL,
	"opening_cash" numeric(10, 2) NOT NULL,
	"closed_at" timestamp with time zone,
	"counted_cash" numeric(10, 2),
	"counted_yape" numeric(10, 2),
	"counted_card" numeric(10, 2),
	"close_note" text,
	"reported_sales" integer,
	"expected_cash" numeric(10, 2),
	"expected_yape" numeric(10, 2),
	"expected_card" numeric(10, 2),
	"id_reviewed_by" integer,
	"reviewed_at" timestamp with time zone,
	"review_note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "cash_shifts_uuid_unique" UNIQUE("uuid")
);
--> statement-breakpoint
ALTER TABLE "sales" ADD COLUMN "shift_uuid" uuid;--> statement-breakpoint
ALTER TABLE "cash_movements" ADD CONSTRAINT "cash_movements_id_created_by_users_id_user_fk" FOREIGN KEY ("id_created_by") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cash_shifts" ADD CONSTRAINT "cash_shifts_id_cashier_users_id_user_fk" FOREIGN KEY ("id_cashier") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cash_shifts" ADD CONSTRAINT "cash_shifts_id_reviewed_by_users_id_user_fk" FOREIGN KEY ("id_reviewed_by") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "cash_movements_shift_idx" ON "cash_movements" USING btree ("shift_uuid");--> statement-breakpoint
CREATE INDEX "cash_shifts_cashier_status_idx" ON "cash_shifts" USING btree ("id_cashier","status");--> statement-breakpoint
CREATE INDEX "cash_shifts_opened_idx" ON "cash_shifts" USING btree ("opened_at");--> statement-breakpoint
CREATE INDEX "sales_shift_idx" ON "sales" USING btree ("shift_uuid");