CREATE TYPE "public"."attendance_correction_status" AS ENUM('pending', 'approved', 'rejected');--> statement-breakpoint
CREATE TYPE "public"."attendance_field" AS ENUM('clock_in', 'clock_out');--> statement-breakpoint
CREATE TYPE "public"."attendance_status" AS ENUM('open', 'closed', 'missing_clock_out');--> statement-breakpoint
CREATE TABLE "attendance_corrections" (
	"id_attendance_correction" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attendance_corrections_id_attendance_correction_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uuid" uuid NOT NULL,
	"attendance_uuid" uuid NOT NULL,
	"field" "attendance_field" NOT NULL,
	"old_value" timestamp with time zone,
	"new_value" timestamp with time zone NOT NULL,
	"reason" text NOT NULL,
	"id_requested_by" integer NOT NULL,
	"status" "attendance_correction_status" DEFAULT 'pending' NOT NULL,
	"id_reviewed_by" integer,
	"reviewed_at" timestamp with time zone,
	"review_note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "attendance_corrections_uuid_unique" UNIQUE("uuid")
);
--> statement-breakpoint
CREATE TABLE "attendance_records" (
	"id_attendance" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attendance_records_id_attendance_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uuid" uuid NOT NULL,
	"id_user" integer NOT NULL,
	"work_date" date NOT NULL,
	"clock_in_at" timestamp with time zone NOT NULL,
	"clock_in_device_at" timestamp with time zone,
	"clock_in_received_at" timestamp with time zone DEFAULT now() NOT NULL,
	"clock_out_at" timestamp with time zone,
	"clock_out_device_at" timestamp with time zone,
	"clock_out_received_at" timestamp with time zone,
	"scheduled_start" timestamp with time zone,
	"scheduled_end" timestamp with time zone,
	"tolerance_min" integer,
	"late_minutes" integer DEFAULT 0 NOT NULL,
	"early_leave_minutes" integer DEFAULT 0 NOT NULL,
	"status" "attendance_status" DEFAULT 'open' NOT NULL,
	"offline" boolean DEFAULT false NOT NULL,
	"time_suspicious" boolean DEFAULT false NOT NULL,
	"is_corrected" boolean DEFAULT false NOT NULL,
	"id_created_by" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "attendance_records_uuid_unique" UNIQUE("uuid")
);
--> statement-breakpoint
CREATE TABLE "work_schedules" (
	"id_work_schedule" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "work_schedules_id_work_schedule_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_user" integer NOT NULL,
	"weekday" integer NOT NULL,
	"start_time" time NOT NULL,
	"end_time" time NOT NULL,
	"tolerance_min" integer DEFAULT 10 NOT NULL,
	"id_updated_by" integer,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "attendance_corrections" ADD CONSTRAINT "attendance_corrections_id_requested_by_users_id_user_fk" FOREIGN KEY ("id_requested_by") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attendance_corrections" ADD CONSTRAINT "attendance_corrections_id_reviewed_by_users_id_user_fk" FOREIGN KEY ("id_reviewed_by") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attendance_records" ADD CONSTRAINT "attendance_records_id_user_users_id_user_fk" FOREIGN KEY ("id_user") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attendance_records" ADD CONSTRAINT "attendance_records_id_created_by_users_id_user_fk" FOREIGN KEY ("id_created_by") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_schedules" ADD CONSTRAINT "work_schedules_id_user_users_id_user_fk" FOREIGN KEY ("id_user") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_schedules" ADD CONSTRAINT "work_schedules_id_updated_by_users_id_user_fk" FOREIGN KEY ("id_updated_by") REFERENCES "public"."users"("id_user") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "attendance_corrections_record_idx" ON "attendance_corrections" USING btree ("attendance_uuid");--> statement-breakpoint
CREATE INDEX "attendance_corrections_status_idx" ON "attendance_corrections" USING btree ("status");--> statement-breakpoint
CREATE INDEX "attendance_user_date_idx" ON "attendance_records" USING btree ("id_user","work_date");--> statement-breakpoint
CREATE INDEX "attendance_date_idx" ON "attendance_records" USING btree ("work_date");--> statement-breakpoint
CREATE INDEX "attendance_status_idx" ON "attendance_records" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX "work_schedules_user_weekday_idx" ON "work_schedules" USING btree ("id_user","weekday");