import { z } from "zod";
import { DNI_PATTERN } from "@/domain/entities/worker";
import { ageOn } from "@/domain/services/birthday";
import { storeDateKey } from "@/domain/value-objects/store-time";
import { idSchema } from "./id";

export const dniSchema = z
  .string()
  .trim()
  .regex(DNI_PATTERN, "El DNI debe tener 8 dígitos");

// YYYY-MM-DD, a real calendar date.
const calendarDateSchema = z.iso.date("Fecha inválida");

// For the birthday gift. An airport worker is an adult of working age.
export const birthDateSchema = calendarDateSchema.refine(
  (value) => {
    const age = ageOn(value, storeDateKey(new Date()));
    return age >= 16 && age <= 80;
  },
  { message: "Revisa la fecha de nacimiento" },
);

// `uuid` is generated by the POS so a registration queued offline is
// idempotent.
export const workerRegisterSchema = z.object({
  uuid: z.uuid(),
  dni: dniSchema,
  fullName: z
    .string()
    .trim()
    .min(3, "Escribe el nombre completo")
    .max(120)
    .transform((value) => value.replace(/\s+/g, " ").toUpperCase()),
  nameSource: z.enum(["api", "manual"]),
  company: z
    .string()
    .trim()
    .min(2, "Escribe la empresa donde trabaja")
    .max(80),
  birthDate: birthDateSchema,
  occurredAt: z.iso.datetime(),
});

export const workerBirthDateSchema = z.object({
  workerId: idSchema,
  birthDate: birthDateSchema,
});

// "Mis puntos": the worker proves who they are with DNI + birth date.
export const workerStatementSchema = z.object({
  dni: dniSchema,
  birthDate: calendarDateSchema,
});

export const discountPolicySchema = z.object({
  maxDiscountedUnitsPerSale: z
    .number()
    .int("Debe ser un número entero")
    .min(1, "Al menos 1 unidad")
    .max(20),
  maxDiscountedSalesPerDay: z
    .number()
    .int("Debe ser un número entero")
    .min(0)
    .max(50),
  pointsPerSol: z.number().min(0).max(100),
  birthdayGiftMaxAmount: z.number().min(0).max(500),
});

export type WorkerRegisterInput = z.infer<typeof workerRegisterSchema>;
